# -*- coding: utf-8 -*-
"""sobel_edges.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1caF1ZhSNoTFofHKHcZr__L7bdxvl0l9z
"""

import matplotlib.pyplot as plt
from skimage import io, filters

image = io.imread('download.jpeg', as_gray=True)

edges = filters.sobel(image)

fig, axes = plt.subplots(ncols=2, figsize=(8, 4))
ax = axes.ravel()
ax[0].imshow(image, cmap=plt.cm.gray)
ax[0].set_title('Original')
ax[1].imshow(edges, cmap=plt.cm.gray)
ax[1].set_title('Edges')
for a in ax:
    a.axis('off')
plt.tight_layout()
plt.show()